apiVersion: etcd.yunxue521.top/v1alpha1
kind: EtcdBackup
metadata:
  name: etcdbackup-sample
spec:
  image: "chenteng/etcd-operator-backup:2.0.2"
  etcdUrl: "http://etcdcluster-sample-0.etcdcluster-sample.default.svc.cluster.local:2379"
  storageType: "s3"
  s3:
    path: "mysqlbak/test.db"  
    endpoint: "192.168.1.189:9000"
    secret: "minio-access-secret"
  oss:
    path: ""
    endpoint: "192.168.1.189:9000"
    secret: "test"
