apiVersion: etcd.yunxue521.top/v1alpha1
kind: EtcdBackup
metadata:
  name: etcdbackup-sample
spec:
  image: "chenteng/etcd-operator-backup:1.0.0"
  etcdUrl: "http://etcdcluster-sample-0.etcdcluster-sample.default.svc.cluster.local:2379"
  storageType: "s3"
  s3:
    path: "foo-bucket"
    s3Secret: "test"
  oss:
    path: ""
    ossSecret: "test"